# Generated by Django 3.2.24 on 2024-02-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_media_link_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_link_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
