# Generated by Django 3.2.24 on 2024-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todo_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='low', max_length=10),
            preserve_default=False,
        ),
    ]
