# Generated by Django 3.2.24 on 2024-03-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='description',
        ),
        migrations.AddField(
            model_name='dream',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dream'),
        ),
    ]
