# Generated by Django 3.2.24 on 2024-02-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='todo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
