# Generated by Django 3.2.24 on 2024-02-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todo_completed_at'),
        ('eventmanagement', '0003_events_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='todo_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todo'),
        ),
    ]
