# Generated by Django 3.2.24 on 2024-02-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0004_alter_events_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='todo_id',
        ),
    ]
