# Generated by Django 3.2.24 on 2024-03-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240303_1614'),
        ('eventmanagement', '0005_remove_events_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dream'),
        ),
    ]
